### ISSUE TITLE
Optifine, performant and epic fight mod not working

### ISSUE THREAD

**Issue by Sebaspc97** [Skullman-G/MC-Dark-Souls#9]
Optifine not working for 1.18.2
Performant not working for 1.16.5 (similar mod to optifine)
Epic fight mod not working for 1.18.2

Cant get pass world loading screen with optifine installed and it wont load main menu with epic fight mod (both 1.18.2)

**Comment by Skullman-G** [comment]
I've noticed this problem too at first, but just thought that it may be due to Optifine not being updated to the newest Forge version like my Mod. But now I will look more into this. Thanks for the info!

**Comment by Skullman-G** [comment]
So the problem with being stuck on the loading screen when running with Optifine has to do with Optifine suppressing the trigger that causes the fade-out-animation. I didn't look into performant on 1.16.5 yet because I want to go more in the direction to support the newest Minecraft version. I still have to figure out the issues with the Epic Fight Mod.

**Comment by Skullman-G** [comment]
Fixed it!
